---
title: "paper"
author: "Maxwel Coura Oliveira"
date: "9/10/2021"
output: html_document
---



```{r}
library(tidyverse)
library(emmeans)
library(glmmTMB)
library(ggtext)
library(lme4)
library(tidymodels)
library(lmerTest)
library(ggthemes)
library(ggrepel)
library(tidytext)
library(rstanarm)
library(brms)
library(bayestestR)
library(BayesFactor)
```

# Load dataset

```{r echo=TRUE, message=FALSE, warning=FALSE}
data <- read_csv("data/SB12.csv")
```

```{r}
glimpse(data)
```

```{r}
new_dt <- 
  data %>% 
  rename (herbicide = other) %>% 
  mutate(
    wt_14 = waterhempcontrol_14/100,
    wt_28 = waterhempcontrol_28/100,
    wt_hv = waterhempcontrol_harvest/100,
    yield_kg = yield_bu * 67.5) %>% 
  mutate(
    wt_14 = 
      case_when(
        waterhempcontrol_14 == 100   ~  0.99,
        TRUE            ~ wt_14),
    wt_28 = case_when(
        waterhempcontrol_28 == 100   ~  0.99,
        waterhempcontrol_28 == 0   ~  0.01,
        TRUE            ~ wt_28)) %>% 
  filter(
    herbicide != "PRE only"
  ) %>% 
  mutate_if(is_character, as.factor) %>% 
  mutate(rep = as.factor(rep),
         year = as.factor(year))
```

```{r}
new_dt |> 
  ggplot(aes(x = herbicide, y = waterhempcontrol_harvest)) +
  geom_boxplot() +
  coord_flip() +
  geom_jitter() +
  facet_grid(year ~ location)
```


```{r}
new_dt |> 
  ggplot(aes(x = herbicide, y = waterhempcontrol_harvest)) +
  geom_boxplot() +
  coord_flip() +
  geom_jitter() +
  facet_grid(year ~ location)
```





# 14 DAT

```{r}
model1 <- brm(wt_14 ~ herbicide +
                (1|rep/location/year),
                  family = Beta(link = "logit", link_phi = "log"),
               warmup = 1000, iter = 2000, chains = 4, 
              control = list(adapt_delta = 0.999, max_treedepth = 11),
               prior = set_prior("student_t(0.1, 0.5, 8)", 
                                 class = "b"),
              seed = 1234,
                  data = new_dt, save_pars = save_pars(all = TRUE))
```




```{r}
summary(model1)
```

```{r}
epred1 <- emmeans(model1, "herbicide", epred = TRUE, cont="pairwise")
```


```{r}
w14_main <- pairs(emmeans(model1, ~ herbicide))

describe_posterior(w14_main,
                   centrality = "mean", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model1)
```

```{r}
epred1$emmeans %>% 
  as_tibble() %>% 
  mutate(DAT = "14 DAT") -> epred1_1
```

```{r}
epred1_1 %>% 
  mutate(herbicide = fct_recode(herbicide,
                                "PRE fb glufosinate + fomesafen + *S*-metolachlor" = "PRE fb glufosinate + fomesafen + S-metolachlor",
                                "PRE fb glufosinate + *S*-metolachlor" = "PRE fb glufosinate + S-metolachlor")) %>% 
  mutate(herbicide = str_remove(herbicide, "PRE fb ")) -> epred1_11
```

```{r}
epred1_11 |> 
  mutate(herbicide = fct_relevel(herbicide,
                                 levels = c("glufosinate", "glufosinate + dimethenamid-P",
                                            "glufosinate + imazethapyr", 
                                            "glufosinate + *S*-metolachlor",
                                            "glufosinate + pyroxasulfone", "glufosinate + acetochlor",
                                            "glufosinate + fomesafen + acetochlor",
                                            "glufosinate + fomesafen + *S*-metolachlor",
                                            "glufosinate + fomesafen"))) |> 
  mutate(emmean = round(emmean, 2)) -> epred1_111
```

```{r}
epred1_111 %>% 
ggplot(aes(x = fct_reorder(herbicide, emmean),
           y = emmean * 100, color = herbicide)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.HPD * 100, ymax = upper.HPD * 100),
                 size = 1.2) +
  coord_flip() +
  facet_grid(~ DAT) +
  geom_text_repel(aes(label = round(emmean*100,1)), size = 3.5,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_nudge_repel(x = 0.3),
                    seed = 465) +
#  scale_color_brewer(palette = "Set1") +
  scale_color_calc() +
  ylim(0, 100) +
  labs(x = NULL, y = "Waterhemp control (%)") +
  theme_bw() +
  theme(axis.text.y = element_markdown(lineheight = 1.2, color = "#333333"),
        axis.text.x = element_markdown(lineheight = 1.2, color = "#333333"),
        axis.title.x = element_blank(),
        strip.text = element_markdown(size = 12, face = "bold"),
        legend.position = "none") -> fig1

#ggsave("figures/Figure 2.png", width = 5, height = 4)
```




# 28 DAT

```{r}
model2 <- brm(wt_28 ~ herbicide +
                (1|rep/location/year),
                  family = Beta(link = "logit", link_phi = "log"),
               warmup = 1000, iter = 2000, chains = 4, 
              control = list(adapt_delta = 0.999, max_treedepth = 11),
               prior = set_prior("student_t(0.1, 0.5, 8)", 
                                 class = "b"),
              seed = 1234,
                  data = new_dt, save_pars = save_pars(all = TRUE))
```

```{r}
summary(model2)
```

```{r}
epred2 <- emmeans(model2, "herbicide", 
                  epred = TRUE, 
                  cont="pairwise"
                  )
```

```{r}
w28_main <- pairs(emmeans(model2, ~ herbicide))

describe_posterior(w28_main,
                   centrality = "median", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model2)
```


```{r}
epred2$emmeans %>% 
  as_tibble() %>% 
  mutate(DAT = "28 DAT") -> epred2_2
```


```{r}
epred2_2 %>% 
  mutate(herbicide = fct_recode(herbicide,
                                "PRE fb glufosinate + fomesafen + *S*-metolachlor" = "PRE fb glufosinate + fomesafen + S-metolachlor",
                                "PRE fb glufosinate + *S*-metolachlor" = "PRE fb glufosinate + S-metolachlor")) %>% 
  mutate(herbicide = str_remove(herbicide, "PRE fb ")) -> epred2_22
```


```{r}
epred2_22|> 
  mutate(herbicide = fct_relevel(herbicide,
                                 levels = c("glufosinate", "glufosinate + dimethenamid-P",
                                            "glufosinate + imazethapyr", 
                                            "glufosinate + *S*-metolachlor",
                                            "glufosinate + pyroxasulfone", "glufosinate + acetochlor",
                                            "glufosinate + fomesafen + acetochlor",
                                            "glufosinate + fomesafen + <i>S</i>-metolachlor",
                                            "glufosinate + fomesafen"))) |> 
  mutate(emmean = round(emmean, 2)) -> epred2_222
```

```{r}
epred2_222 %>% 
  ggplot(aes(x = fct_reorder(herbicide, emmean),
           y = emmean * 100, color = herbicide)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.HPD * 100, ymax = upper.HPD * 100),
                 size = 1.2) +
  coord_flip() +
  facet_grid(~ DAT) +
  geom_text_repel(aes(label = round(emmean*100,1)), size = 3.5,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_nudge_repel(x = 0.3),
                    seed = 465) +
#  scale_color_brewer(palette = "Set1") +
  scale_color_calc() +
  ylim(0, 100) +
  labs(x = NULL, y = "Waterhemp control (%)") +
  theme_bw() +
  theme(axis.text.y = element_markdown(lineheight = 1.2, color = "#333333"),
        axis.text.x = element_markdown(lineheight = 1.2, color = "#333333"),
        axis.title.y = element_blank(),
        strip.text = element_markdown(size = 11, face = "bold"),
        legend.position = "none") -> fig2
#ggsave("figures/Figure 22.png", width = 5, height = 4)
```



```{r}
library(patchwork)
```

```{r}
fig1 / fig2 +
  plot_annotation(tag_levels = 'A')

ggsave("figures/Figure 3.png", width = 6, height = 8)
```


# Figures

```{r}
epred1_1 %>% 
  bind_rows(epred2_2) %>% 
#  bind_rows(epred5) |> 
  mutate(herbicide = fct_recode(herbicide,
                                "PRE fb glufosinate + fomesafen + *S*-metolachlor" = "PRE fb glufosinate + fomesafen + S-metolachlor",
                                "PRE fb glufosinate + *S*-metolachlor" = "PRE fb glufosinate + S-metolachlor")) %>% 
  mutate(herbicide = str_remove(herbicide, "PRE fb ")) -> epred_wt
```

```{r}
epred_wt |> 
  mutate(herbicide = fct_relevel(herbicide,
                                 levels = c("glufosinate", "glufosinate + dimethenamid-P",
                                            "glufosinate + imazethapyr", 
                                            "glufosinate + *S*-metolachlor",
                                            "glufosinate + pyroxasulfone", "glufosinate + acetochlor",
                                            "glufosinate + fomesafen + acetochlor",
                                            "glufosinate + fomesafen + *S*-metolachlor",
                                            "glufosinate + fomesafen"))) -> epred_wt1
```


```{r}
epred_wt %>% 
ggplot(aes(x = fct_reorder(herbicide, emmean),
           y = emmean * 100, color = herbicide)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.HPD * 100, ymax = upper.HPD * 100),
                 size = 1.2) +
  coord_flip() +
  facet_grid(~ DAT) +
  geom_text_repel(aes(label = round(emmean*100,1)), size = 3.5,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_nudge_repel(x = 0.3),
                    seed = 465) +
#  scale_color_brewer(palette = "Set1") +
  scale_color_calc() +
  ylim(0, 100) +
  labs(x = NULL, y = "Waterhemp control (%)") +
  theme_bw() +
  theme(axis.text.y = element_markdown(),
        strip.text = element_markdown(size = 11, face = "bold"),
        legend.position = "none",
        plot.background = element_rect(fill = "#F5F5F5"),
        panel.background = element_rect(fill = "#F5F5F5"),
        axis.text = element_markdown(color = "#333333")) 

#ggsave("figures/Figure 2.png", width = 9, height = 4)
```

# Yield

```{r}
new_dt %>% 
  ggplot(aes(x = herbicide,  y = yield_bu)) +
  geom_boxplot() +
  ylim(0, 70) +
  coord_flip()
```

```{r}
new_dt %>% 
  group_by(herbicide) |> 
  summarise(yield = mean(yield_bu, na.rm = TRUE),
            sd = sd(yield_bu, na.rm = TRUE))
```




```{r}
model4 <- brm(yield_bu ~ herbicide +
                (1|rep/location/year), 
                  family = gaussian(),
               warmup = 1000, iter = 2000, chains = 4, 
              control = list(adapt_delta = 0.999, max_treedepth = 11),
               prior = set_prior("student_t(0.1, 2, 8)", 
                                 class = "b"),
              seed = 1234,
                  data = new_dt, save_pars = save_pars(all = TRUE))
```

```{r}
summary(model4)
```



```{r}
yield_main <- pairs(emmeans(model4, ~ herbicide))

describe_posterior(yield_main,
                   centrality = "median", dispersion = TRUE,
                   ci = .95, ci_method = "hdi",
                   test = c("bayesfactor"),
                   bf_prior = model4)
```


```{r}
epred4 |> as_tibble() %>% 
  mutate(herbicide = fct_recode(herbicide,
           "PRE fb glufosinate + fomesafen + *S*-metolachlor" = "PRE fb glufosinate + fomesafen + S-metolachlor",
           "PRE fb glufosinate + *S*-metolachlor" = "PRE fb glufosinate + S-metolachlor")) %>% 
  mutate(herbicide = str_remove(herbicide, "PRE fb ")) -> epred4_wt
```

```{r}
epred4_wt %>% 
  mutate(herbicide = fct_relevel(herbicide,
                                 levels = c("glufosinate", "glufosinate + dimethenamid-P",
                                            "glufosinate + imazethapyr", 
                                            "glufosinate + *S*-metolachlor",
                                            "glufosinate + pyroxasulfone", "glufosinate + acetochlor",
                                            "glufosinate + fomesafen", 
                                            "glufosinate + fomesafen + acetochlor",
                                            "glufosinate + fomesafen + *S*-metolachlor"))) -> epred4_wt1
```



```{r}
epred4_wt1 %>%
  ggplot(aes(x = fct_reorder(herbicide, emmean),
           y = emmean, color = herbicide)) +
  geom_point(size = 2) +
  geom_linerange(aes(ymin = lower.HPD, ymax = upper.HPD),
                 size = 1.2) +
  coord_flip() +
  geom_text_repel(aes(label = round(emmean,1)), size = 3.5,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_nudge_repel(x = 0.3),
                    seed = 465) +
  scale_color_calc() +
  scale_y_continuous(limits = c(0,75), breaks = seq(0, 75, 15)) +
  labs(x = NULL, y = expression(paste("Soybean yield (bu acre"^"-1",")"))) +
  theme_bw() +
  theme(axis.text.y = element_markdown(),
        strip.text = element_markdown(size = 11),
        legend.position = "none",
        plot.background = element_rect(fill = "#F9F6EE"),
        panel.background = element_rect(fill = "#F9F6EE"),
        axis.text = element_markdown(color = "#333333")) -> fig2

ggsave("figures/Figure 5.png", width = 6, height = 4)
```


